In [22]:
from tensorflow.keras.preprocessing.text import one_hot

In [23]:
sent = [ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good'
]

In [24]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [25]:
## define the vocabulary size
voc_size = 10000

In [26]:
### One Hot Representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[8793, 3795, 1029, 4264],
 [8793, 3795, 1029, 9336],
 [8793, 3162, 1029, 6688],
 [2053, 2395, 778, 9196, 9156],
 [2053, 2395, 778, 9196, 5487],
 [7293, 8793, 8655, 1029, 3245],
 [7413, 7308, 1331, 9196]]

In [27]:
## word Embedding representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [28]:
import numpy as np


In [29]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs) 

[[   0    0    0    0 8793 3795 1029 4264]
 [   0    0    0    0 8793 3795 1029 9336]
 [   0    0    0    0 8793 3162 1029 6688]
 [   0    0    0 2053 2395  778 9196 9156]
 [   0    0    0 2053 2395  778 9196 5487]
 [   0    0    0 7293 8793 8655 1029 3245]
 [   0    0    0    0 7413 7308 1331 9196]]


In [30]:
## feature representation
dim = 10

In [33]:
model = Sequential()
model.add(Embedding(voc_size, dim))
model.compile('adam', 'mse')

In [34]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
max_len = 10

model = Sequential()
model.add(Embedding(voc_size, dim, input_shape=(max_len,)))  # Specify input shape
model.compile(optimizer='adam', loss='mse')
model.summary()

d:\RNN\venv\lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 10, 10)         │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)